### ISSUE TITLE
save xlocation as polygon when applicable

### ISSUE THREAD

**Issue by DanielJDufour** [hotosm/fmtm#2508]
**Describe the bug**
xlocation should be uploaded as polygon from web-forms when a polygon is used for the features

**To Reproduce**

**Expected behavior**
`<xlocation><xlocation>` tag in xml submission should be filled in, in format shown here: https://github.com/hotosm/fmtm/issues/2493#issuecomment-2875825770 

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
Originally reported by @Anuj-Gupta4 [here](https://github.com/hotosm/fmtm/issues/2493#issuecomment-2875825770)

**Comment by spwoodcock** [comment]
I think we already have some logic in place to convert from geojson --> javarosa geom and back.

Hopefully frontend code available, otherwise definitely on the backend 👍

**Comment by NSUWAL123** [comment]
The xlocation works completely fine for existing entities, but the xlocation is still null for new entities

**Comment by DanielJDufour** [comment]
Thank you for catching this!

**Comment by DanielJDufour** [comment]
I've had some difficulty reproducing this in my local dev environment.  Here's the steps I took:
1. Click `COLETAR NOVO PONTO`
2. Trace the polygon
3. Click "PROCEED" after it asks if the geometry is correct
4. Fill out the form
5. xlocation is in the payload posted to `"http://api.fmtm.localhost:7050/submission?project_id=3"`

I've done this twice now without problems.  I'm thinking I'm missing something and the issue might be:
- Some sort of race condition where the form opens before the new entity is created, which maybe could happen on slower networks
- Maybe there's different steps to creating the entity polygon
- Some difference in the way browsers behave that is causing this (Chrome vs. Firefox, etc)
- Some difference in the form definition that I didn't plan for

@NSUWAL123 , any suggestions you can make would be most appreciated!  Do you have this problem in all browsers?  Is this a problem with all projects?  Could you share a link to the project?  Thank you again for catching this!!

**Comment by spwoodcock** [comment]
More info would be useful yeah - perhaps this is actually solved now 👍 

You could be right for the first bullet point - possible race condition as the entity does not exist yet.
If so, then this might actually be fixed. The logic was updated to generate the entity UUID on the frontend (instantly) and pass into the backend, instead of the roundtrip required for (1) creating the new entity (2) waiting for the response (3) using the new entity UUID provided by the backend in the web form

**Comment by manjitapandey** [comment]
X-location is not visible for points and line data though. I think we can track this on separate issue.

**Comment by manjitapandey** [comment]
reopening as Still facing the issue in case of existing feature whereas the x-location is passed in case of new feature.

**Comment by Sujanadh** [comment]
The problem with xlocation not being calculated is we don't save every geometry of the entities of the project while creating the project in our own `odk_entities` table. We are only storing the geometry of the newly created feature. As in ODK Collect, we have logic that pulls the geometry of the selected existing entity from central `instance('features')/root/item[name=${feature}]/geometry,` and calculates `xlocation`.  But, in our web form, we can't do that, as we can't have direct XPath from central to calculate when the form is loaded.

The probable solutions would be
1. pull data from central (`features.csv`) and link it to web form and calculate it when form is loaded similarly to ODK Collect (Not sure though)
2. The other option would be to save all the entities and their geometry in our database.

@spwoodcock @DanielJDufour @NSUWAL123

**Comment by manjitapandey** [comment]
In case of polygon when user is not logged in, the x-location is no populated. So reopening this issue again. 

![Image](https://github.com/user-attachments/assets/7cdd95bb-e00a-4162-aa01-7d0f2e27bc82)

cc: @NSUWAL123
