### ISSUE TITLE
merge of dev into main is broken

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#723]
Since I'm trying to update the prod server, I did a test merge of development into main. Here's how to reproduce this.

1. Clone FMTM into /tmp/test-merge
2. In test-merge, do a 'git merge origin/development', there's 4 file conflicts.
3. Fix the conflicts
4. docker-compose down -v && docker-compose build --no-cache
5. docker-compose up. You'll see these errors: 

fmtm_main        | [webpack-cli] Failed to load '/app/webpack.config.js' config
fmtm_main        | [webpack-cli] Error: Cannot find module 'workbox-webpack-plugin'
fmtm_main        | Require stack:
fmtm_main        | - /app/webpack.config.js
fmtm_main        | - /app/node_modules/webpack-cli/lib/webpack-cli.js
fmtm_main        | - /app/node_modules/webpack-cli/lib/bootstrap.js
fmtm_main        | - /app/node_modules/webpack-cli/bin/cli.js
fmtm_main        | - /app/node_modules/webpack/bin/webpack.js
fmtm_main        |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
fmtm_main        |     at Module._load (node:internal/modules/cjs/loader:920:27)
fmtm_main        |     at Module.require (node:internal/modules/cjs/loader:1141:19)
fmtm_main        |     at require (node:internal/modules/cjs/helpers:110:18)
fmtm_main        |     at Object.<anonymous> (/app/webpack.config.js:9:30)
fmtm_main        |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
fmtm_main        |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
fmtm_main        |     at Module.load (node:internal/modules/cjs/loader:1117:32)
fmtm_main        |     at Module._load (node:internal/modules/cjs/loader:958:12)
fmtm_main        |     at Module.require (node:internal/modules/cjs/loader:1141:19) {
fmtm_main        |   code: 'MODULE_NOT_FOUND',
fmtm_main        |   requireStack: [
fmtm_main        |     '/app/webpack.config.js',
fmtm_main        |     '/app/node_modules/webpack-cli/lib/webpack-cli.js',
fmtm_main        |     '/app/node_modules/webpack-cli/lib/bootstrap.js',
fmtm_main        |     '/app/node_modules/webpack-cli/bin/cli.js',
fmtm_main        |     '/app/node_modules/webpack/bin/webpack.js'
fmtm_main        |   ]
fmtm_main        | }

**Comment by varun2948** [comment]
@robsavoye need to rebuild the whole application can u confirm it ?

**Comment by robsavoye** [comment]
I did a test merge after approving the PRs this morning. I do that in a clean clone, instead of my working directories. So yes, I rebuilt the entire docker container.

**Comment by varun2948** [comment]
@robsavoye i just tested on a branch with the base as main and pulled development and fixed a merge issue "varun-test-main" I have fixed the merge issue that was coming I think pulling it and mergin it to main would fix it.

**Comment by robsavoye** [comment]
I still have the same problem. I tried just your branch with no merging, same problem. Is this the same issue as npm not updating ?

**Comment by varun2948** [comment]
no you dont have to update npm package the docker should automatically do it

**Comment by robsavoye** [comment]
the development branch has been merged to main, and pushed to the production server.
